### ISSUE TITLE
根据服务端部署服务器程序,客户端在4Gwangl出现了一些问题,请教一下

### ISSUE THREAD

**Issue by ITLyc** [ddssingsong/webrtc_android#11]
E/stun_port.cc: (line 284): Port[b923cb28:audio:1:0:local:Net[lo:127.0.0.0/8:Loopback:id=1]]: UDP send of 96 bytes failed with error 22
09-23 18:48:40.416 2420-8900/com.yunxin.webrtc W/port.cc: (line 1246): Conn[b962fc58:audio:Net[lo:127.0.0.0/8:Loopback:id=1]:3+huZJtc:1:0:local:udp:127.0.0.1:58095->FMAsLrZK:1:1686052607:stun:udp:1.193.36.223:55499|C--I|-|0|0|7241540810644667902|-]: Failed to send STUN ping  err=-1 id=73724d7458506f784a543263
09-23 18:48:40.416 2420-8900/com.yunxin.webrtc I/port.cc: (line 1756): Conn[b962fc58:audio:Net[lo:127.0.0.0/8:Loopback:id=1]:3+huZJtc:1:0:local:udp:127.0.0.1:58095->FMAsLrZK:1:1686052607:stun:udp:1.193.36.223:55499|C--I|-|0|0|7241540810644667902|-]: Sent STUN ping, id=73724d7458506f784a543263, use_candidate=0, nomination=0
09-23 18:48:40.466 2420-8900/com.yunxin.webrtc I/port.cc: (line 1756): Conn[b96fc4b0:audio:Net[rmnet_data0:2409:8944:280:da8::/64:Cellular:id=4]:xLy1eMHD:1:0:local:udp:[2409:8944:280:da8:b014:d82f:8f0f:eab2]:35070->r+Lqy4Mi:1:2122005759:local:udp:[::1]:39111|C--I|-|0|0|9113945341073183230|-]: Sent STUN ping, id=6234667873452b6d46663148, use_candidate=0, nomination=0
09-23 18:48:40.486 2420-8900/com.yunxin.webrtc E/stun_port.cc: (line 561): sendto : [0x00000016] Invalid argument
09-23 18:48:40.516 2420-8900/com.yunxin.webrtc I/port.cc: (line 1756): Conn[b96fda40:audio:Net[rmnet_data0:10.152.174.88/30:Cellular:id=3]:x0AxrwmI:1:0:local:udp:10.152.174.90:53213->7KDriU1s:1:2121932543:local:udp:127.0.0.1:47844|C--I|-|0|0|9113630880747503102|-]: Sent STUN ping, id=794a496765566d77734d4471, use_candidate=0, nomination=0
09-23 18:48:40.536 2420-8900/com.yunxin.webrtc I/turn_port.cc: (line 1315): Port[b929ef30:audio:1:0:relay:Net[rmnet_data0:10.152.174.88/30:Cellular:id=3]]: TURN allocate request sent, id=416d637661626d6846366e42

![7A6CCD1A-EC84-436D-959F-5B067C64FE61](https://user-images.githubusercontent.com/31461424/65420188-1c3d7980-de33-11e9-9882-fe5d89d0c7a4.png)
帮我看一下吧,谢谢谢谢

**Comment by ddssingsong** [comment]
turn服务器配置有问题
