### ISSUE TITLE
Video quality improvement 

### ISSUE THREAD

**Issue by msh-nayan** [ddssingsong/webrtc_android#17]
Hello, 
Thanks for the library. 
I'd like to improve the video quality (during video call). how can I improve the quality?

**Comment by kulnaman** [comment]
@msh-nayan hi, did you were able to improve the video quality ? any guidance will be appreciated.

**Comment by ddssingsong** [comment]
change :   
```
   public static final int VIDEO_RESOLUTION_WIDTH = 320;
    public static final int VIDEO_RESOLUTION_HEIGHT = 240;
    public static final int FPS = 15;
```
