### ISSUE TITLE
How to increase fps?

### ISSUE THREAD

**Issue by minmax9493** [ddssingsong/webrtc_android#24]
Thanks for library.
 I' m testing now your WebRTC demo project. Every thing is god, code well organized, but the fps is too low. How can I increase it?

**Comment by minmax9493** [comment]
I found the answer for my question. It was configured in `CallSession`.  FPS was set 10 there, now i've changed it to 20. Is there any effect If I increase it, is there any reason for putting fps = 10 @ddssingsong ?

**Comment by ddssingsong** [comment]
yes
