### ISSUE TITLE
Sending message using DataChannel

### ISSUE THREAD

**Issue by msh-nayan** [ddssingsong/webrtc_android#29]
Hello, 
Thanks for this beautiful library & code sample. 

I'm using your NodeJS server and on client side, I'm using the sample code which uses NodeJS server. 

I can send text message from one peer to another during Audio/Video call (between 2 peers) using DataChannel but problem occurs while conference call. Assume 3 peers are connected to conference call. When I need to send message to other 2 Peers; one of these two peer receives the message, other one doesn't. 

can you please, work on this message sending issue? I'd be helpful... 

Thanks

**Comment by ddssingsong** [comment]
you can search linphone for that
