### ISSUE TITLE
socket not opening in Android webrtc_android app

### ISSUE THREAD

**Issue by sunilkumarjena21** [ddssingsong/webrtc_android#34]
Server Running perfectly fine on IP = "52.167.201.188";

Tested on webrtc_android app:-
webSocket.connect(); returns connectFlag=false & socket not opening in webrtc_android app.So that login was unsuccessful after input the user name & tapping enter.

You can replace the IP like this in Android webrtc_android app.

`public class Urls {

//    private final static String IP = "192.168.2.111";
public final static String IP = "52.167.201.188";`
in Android webrtc_android app & Test.

Please guide.

Thanks in advance

**Comment by ddssingsong** [comment]
ok
