### ISSUE TITLE
I can not see the opponent video

### ISSUE THREAD

**Issue by Jinqianv** [ddssingsong/webrtc_android#4]
Hello, are you still under development?
I want your reply. thanks.

**Comment by ddssingsong** [comment]
Ok.  My server is broken. You may need to build your own server and configure signaling and stun servers.

**Comment by chnouman** [comment]
@ddssingsong setup your server, please.

**Comment by ddssingsong** [comment]
this is a example : [https://118.25.25.147#123456789](https://118.25.25.147#123456789)， Visit only in China

**Comment by chnouman** [comment]
hmm but I'm not from china. Setting up coturn seems to be a big headache.

**Comment by ddssingsong** [comment]
maybe you can try   [https://appr.tc/](https://appr.tc/)，you can get stun and turn url 
like this
```
 "iceServers": [
    {
      "urls": [
        "stun:66.102.1.127:19302",
        "stun:[2a00:1450:400c:c06::7f]:19302"
      ]
    },
    {
      "urls": [
        "turn:74.125.140.127:19305?transport=udp",
        "turn:[2a00:1450:400c:c08::7f]:19305?transport=udp",
        "turn:74.125.140.127:19305?transport=tcp",
        "turn:[2a00:1450:400c:c08::7f]:19305?transport=tcp"
      ],
      "username": "CKfe+OoFEgYMoDQmTDwYzc/s6OMTIICjBQ",
      "credential": "uvmFFMpJ18rnYfl7leXidvY4QOo=",
      "maxRateKbps": "8000"
    }
  ]
```

**Comment by msh-nayan** [comment]
> maybe you can try https://appr.tc/，you can get stun and turn url
> like this
> 
> ```
>  "iceServers": [
>     {
>       "urls": [
>         "stun:66.102.1.127:19302",
>         "stun:[2a00:1450:400c:c06::7f]:19302"
>       ]
>     },
>     {
>       "urls": [
>         "turn:74.125.140.127:19305?transport=udp",
>         "turn:[2a00:1450:400c:c08::7f]:19305?transport=udp",
>         "turn:74.125.140.127:19305?transport=tcp",
>         "turn:[2a00:1450:400c:c08::7f]:19305?transport=tcp"
>       ],
>       "username": "CKfe+OoFEgYMoDQmTDwYzc/s6OMTIICjBQ",
>       "credential": "uvmFFMpJ18rnYfl7leXidvY4QOo=",
>       "maxRateKbps": "8000"
>     }
>   ]
> ```

@ddssingsong , so i can use this `iceServers` as my STUN & TURN url but where should I place that value ?

**Comment by Edison4mobile** [comment]
Opponent video is not showing even I set correct turn & stun server.
