### ISSUE TITLE
即使什么都不渲染，eglSwapBuffers后得到的是黑色背景

### ISSUE THREAD

**Issue by wei-kris** [ddssingsong/webrtc_android#66]
我希望把视频中指定的颜色透明，当前在GLES工作之前，SurfaceView是透明的 ， 但是只要EGL14.eglSwapBuffers(eglDisplay, eglSurface);执行之后就黑屏了 ，即使什么都没有渲染(比如在片元着色器中操作，或者直接在java代码中不去drawFrame)，我想知道为什么eglSwapBuffers后就全部是黑色的了 ？

<img width="908" alt="image" src="https://user-images.githubusercontent.com/704748/202848750-376f3d4c-154a-425e-94cf-3cb1c1f31106.png">

感谢任何帮助！

**Comment by ddssingsong** [comment]
glclearColor make it

**Comment by wei-kris** [comment]
> glclearColor make it

glclearColor的alpha也是0，不知道会不会是因为SurfaceViewRenderer集成的是SurfaceView而不是GLSurfaceView。

**Comment by ddssingsong** [comment]
maybe it should Change the order of the two lines of code
GLES.glClearcolor()
GLES.glClear()

**Comment by wei-kris** [comment]
> maybe it should Change the order of the two lines of code GLES.glClearcolor() GLES.glClear()

经测试调整顺序不能解决这个问题

**Comment by wei-kris** [comment]
已解决，SurfaceViewRenderer的init函数configAttributes参数改为EglBase.CONFIG_RGBA。谢谢
