### ISSUE TITLE
信令交换出现问题

### ISSUE THREAD

**Issue by daybreaksunrise** [ddssingsong/webrtc_android#7]
我给服务器发送的IceCandidate之后
PC端那边总是显示以下错误是什么原因：
Uncaught (in promise) DOMException: Failed to execute 'addIceCandidate' on 'RTCPeerConnection': Error processing ICE candidate

是我的peerPeerConnection创建错误了吗

**Comment by ddssingsong** [comment]
have already been solved

**Comment by EchoXBR** [comment]
这个是怎么解决的？
