### ISSUE TITLE
unknown scheme: https 

### ISSUE THREAD

**Issue by chnouman** [ddssingsong/webrtc_android#8]
I have deployed my Node js server on firebase and get the Url and replaced WSS inside app. I'm getting this error: 
```
E/dds_JavaWebSocket: java.lang.IllegalArgumentException: unknown scheme: https
E/dds_JavaWebSocket: onClose:unknown scheme: https
```

Localy it is working fine when I run node js server locally and replace local ip inside app.

**Comment by ddssingsong** [comment]
If WSS is not used as a proxy for reverse proxy, WS should be used

**Comment by chnouman** [comment]
yes thanks buddy wss://xyz.com works form me

**Comment by chnouman** [comment]
Great work by the way thanks alot
